import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env] 
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 23
dimensions.columns = 100
dimensions.lines = 25

decorations = "transparent"
startup_mode = "Maximized"
opacity = 0.8
blur = true


[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 17

[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u0013"


[[keyboard.bindings]]
key = "F"
mods = "Command"
chars = "\u0010"

[[keyboard.bindings]]
key = "F"
mods = "Command|Shift"
chars = "\u0009"
